# Generated by Django 5.2.7 on 2025-10-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_genre_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
    ]
