# Generated by Django 5.2.7 on 2025-10-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'режисер',
                'verbose_name_plural': 'режисеры',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='library_app.director', verbose_name='режисер'),
        ),
        migrations.CreateModel(
            name='DirectorMoviesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_movie', to='library_app.director', verbose_name='директор')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_movie', to='library_app.movie', verbose_name='фильм')),
            ],
            options={
                'verbose_name': 'фильм режиссера',
                'verbose_name_plural': 'фильмы режиссера',
                'unique_together': {('director', 'director')},
            },
        ),
    ]
