# Generated by Django 5.2.7 on 2025-10-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_director_alter_movie_director_directormoviesitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectorMoviesItem',
        ),
    ]
