# Generated by Django 5.2.7 on 2025-10-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_delete_directormoviesitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
    ]
