# Generated by Django 5.2.7 on 2025-10-30 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_remove_movie_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message='Рейтинг не может быть меньше 0'), django.core.validators.MaxValueValidator(5.0, message='Рейтинг не может быть больше 5')], verbose_name='Рейтинг (0.0-5,0)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800, message='Год должен быть не меньше 1800'), django.core.validators.MaxValueValidator(2100, message='Год не может быть из будущего')], verbose_name='Год выпуска'),
        ),
    ]
