# Generated by Django 5.2.7 on 2025-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_movie_rating_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=0.0, verbose_name='Рейтинг (0.0-5,0)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
