# Generated by Django 5.2.7 on 2025-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_alter_movie_rating_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5')], default=0.0, verbose_name='Рейтинг'),
        ),
    ]
